# Generated by Django 5.2.12 on 2026-03-27 18:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pretixbase', '0299_alter_customer_locale_alter_user_locale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterposCashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('counted_cash', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(default='open', max_length=12)),
                ('close_notes', models.TextField()),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_betterpos_sessions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_cash_sessions', to='pretixbase.event')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_betterpos_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS cash session',
                'verbose_name_plural': 'POS cash sessions',
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='BetterposCashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_cash_movements', to='pretixbase.event')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betterpos_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pretix_betterpos.betterposcashsession')),
            ],
            options={
                'verbose_name': 'POS cash movement',
                'verbose_name_plural': 'POS cash movements',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BetterposRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_registers', to='pretixbase.event')),
            ],
            options={
                'verbose_name': 'POS register',
                'verbose_name_plural': 'POS registers',
                'ordering': ('event', 'code'),
                'permissions': [('can_view_pos', 'Can view POS interface'), ('can_sell_pos', 'Can create POS sales'), ('can_discount_pos', 'Can apply POS discounts'), ('can_cancel_unpaid_pos', 'Can cancel unpaid POS orders'), ('can_refund_pos', 'Can refund paid POS orders'), ('can_cash_move_pos', 'Can register POS cash movements'), ('can_session_control_pos', 'Can open/close POS sessions'), ('can_reconcile_pos', 'Can reconcile POS sessions'), ('can_manage_registers_pos', 'Can manage POS registers'), ('can_view_audit_pos', 'Can view POS audit log')],
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.AddField(
            model_name='betterposcashsession',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='pretix_betterpos.betterposregister'),
        ),
        migrations.CreateModel(
            name='BetterposCartSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('snapshot_payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_cart_snapshots', to='pretixbase.event')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_cart_snapshots', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_snapshots', to='pretix_betterpos.betterposregister')),
            ],
            options={
                'verbose_name': 'POS cart snapshot',
                'verbose_name_plural': 'POS cart snapshots',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BetterposActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betterpos_action_logs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_action_logs', to='pretixbase.event')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betterpos_action_logs', to='pretixbase.order')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betterpos_action_logs', to='pretixbase.orderpayment')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='pretix_betterpos.betterposcashsession')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='pretix_betterpos.betterposregister')),
            ],
            options={
                'verbose_name': 'POS action log',
                'verbose_name_plural': 'POS action logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BetterposRegisterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('role_at_register', models.CharField(default='cashier', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_assignments', to='pretixbase.event')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pretix_betterpos.betterposregister')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS register assignment',
                'verbose_name_plural': 'POS register assignments',
                'ordering': ('register', 'user'),
            },
        ),
        migrations.CreateModel(
            name='BetterposTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('state', models.CharField(default='draft', max_length=32)),
                ('external_reference', models.CharField(max_length=120)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_transactions', to='pretixbase.event')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betterpos_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betterpos_transactions', to='pretixbase.order')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='betterpos_transactions', to='pretixbase.orderpayment')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pretix_betterpos.betterposregister')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pretix_betterpos.betterposcashsession')),
            ],
            options={
                'verbose_name': 'POS transaction',
                'verbose_name_plural': 'POS transactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='betterposcashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('register',), name='btpos_open_session_reg_uq'),
        ),
        migrations.AddIndex(
            model_name='betterposactionlog',
            index=models.Index(fields=['event', 'action_type'], name='betterpos_log_event_action_idx'),
        ),
        migrations.AddIndex(
            model_name='betterposactionlog',
            index=models.Index(fields=['event', 'created_at'], name='btpos_log_event_created_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='betterposregisterassignment',
            unique_together={('event', 'register', 'user')},
        ),
        migrations.AddIndex(
            model_name='betterpostransaction',
            index=models.Index(fields=['event', 'state'], name='betterpos_tx_state_idx'),
        ),
        migrations.AddIndex(
            model_name='betterpostransaction',
            index=models.Index(fields=['register', 'created_at'], name='betterpos_tx_reg_created_idx'),
        ),
    ]
