# Generated by Django 5.2.12 on 2026-04-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_betterpos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterposSelfserviceCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('phone', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='created', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_selfservice_checkouts', to='pretixbase.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betterpos_selfservice_checkouts', to='pretixbase.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betterpos_selfservice_checkouts', to='pretixbase.orderpayment')),
            ],
            options={
                'verbose_name': 'POS selfservice checkout',
                'verbose_name_plural': 'POS selfservice checkouts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='betterposselfservicecheckout',
            index=models.Index(fields=['event', 'state'], name='btpos_ss_event_state_idx'),
        ),
        migrations.AddIndex(
            model_name='betterposselfservicecheckout',
            index=models.Index(fields=['event', 'created_at'], name='btpos_ss_event_created_idx'),
        ),
    ]
